kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: innloggingsinfo
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{version}}
  ingresses:
  {{#each ingresses}}
     - "{{this}}"
  {{/each}}
  vault:
    enabled: true
  liveness:
    path: innloggingsinfo/internal/isAlive
    port: 8080
    initialDelay: 10
  port: 8080
  prometheus:
    enabled: true
    path: innloggingsinfo/internal/metrics
  readiness:
    path: innloggingsinfo/internal/isAlive
    port: 8080
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
