kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: innloggingsinfo
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{version}}
  ingresses: {{ingresses}}
  vault:
    enabled: true
  liveness:
    path: innloggingsinfo/internal/isAlive
    port: 8080
    initialDelay: 10
  port: 8080
  prometheus:
    enabled: true
    path: innloggingsinfo/internal/metrics
  readiness:
    path: innloggingsinfo/internal/isReady
    port: 8080
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      memory: 512Mi