kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: innloggingsinfo
  namespace: min-side
  labels:
    team: min-side
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{version}}
  ingresses:
    - "https://www.dev.nav.no/innloggingsinfo"
  envFrom:
    - secret: innloggingsinfo-secrets
  liveness:
    path: innloggingsinfo/internal/isAlive
    port: 8080
    initialDelay: 10
  port: 8080
  prometheus:
    enabled: true
    path: innloggingsinfo/internal/metrics
  readiness:
    path: innloggingsinfo/internal/isReady
    port: 8080
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "50m"
      memory: 384Mi
